# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 569)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(6, 3, 3, 3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layButtons = QtWidgets.QHBoxLayout()
        self.layButtons.setContentsMargins(-1, 3, -1, -1)
        self.layButtons.setSpacing(3)
        self.layButtons.setObjectName("layButtons")
        self.btnCheckConnection = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCheckConnection.sizePolicy().hasHeightForWidth())
        self.btnCheckConnection.setSizePolicy(sizePolicy)
        self.btnCheckConnection.setMinimumSize(QtCore.QSize(0, 0))
        self.btnCheckConnection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnCheckConnection.setObjectName("btnCheckConnection")
        self.layButtons.addWidget(self.btnCheckConnection)
        self.btnConfiguration = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConfiguration.sizePolicy().hasHeightForWidth())
        self.btnConfiguration.setSizePolicy(sizePolicy)
        self.btnConfiguration.setMinimumSize(QtCore.QSize(0, 0))
        self.btnConfiguration.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnConfiguration.setIconSize(QtCore.QSize(12, 12))
        self.btnConfiguration.setObjectName("btnConfiguration")
        self.layButtons.addWidget(self.btnConfiguration)
        self.btnSaveConfiguration = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveConfiguration.sizePolicy().hasHeightForWidth())
        self.btnSaveConfiguration.setSizePolicy(sizePolicy)
        self.btnSaveConfiguration.setMinimumSize(QtCore.QSize(0, 0))
        self.btnSaveConfiguration.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnSaveConfiguration.setObjectName("btnSaveConfiguration")
        self.layButtons.addWidget(self.btnSaveConfiguration)
        self.btnProposals = QtWidgets.QPushButton(self.groupBox)
        self.btnProposals.setObjectName("btnProposals")
        self.layButtons.addWidget(self.btnProposals)
        self.btnActions = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnActions.sizePolicy().hasHeightForWidth())
        self.btnActions.setSizePolicy(sizePolicy)
        self.btnActions.setMinimumSize(QtCore.QSize(90, 0))
        self.btnActions.setObjectName("btnActions")
        self.layButtons.addWidget(self.btnActions)
        self.btnAbout = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAbout.sizePolicy().hasHeightForWidth())
        self.btnAbout.setSizePolicy(sizePolicy)
        self.btnAbout.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAbout.setMaximumSize(QtCore.QSize(100000, 100000))
        self.btnAbout.setBaseSize(QtCore.QSize(0, 0))
        self.btnAbout.setAutoFillBackground(False)
        self.btnAbout.setFlat(False)
        self.btnAbout.setObjectName("btnAbout")
        self.layButtons.addWidget(self.btnAbout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layButtons.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.layButtons)
        self.layHardwareWallet = QtWidgets.QHBoxLayout()
        self.layHardwareWallet.setContentsMargins(0, 3, -1, 3)
        self.layHardwareWallet.setSpacing(3)
        self.layHardwareWallet.setObjectName("layHardwareWallet")
        self.btnHwCheck = QtWidgets.QPushButton(self.groupBox)
        self.btnHwCheck.setIconSize(QtCore.QSize(12, 12))
        self.btnHwCheck.setShortcut("")
        self.btnHwCheck.setObjectName("btnHwCheck")
        self.layHardwareWallet.addWidget(self.btnHwCheck)
        self.btnHwDisconnect = QtWidgets.QPushButton(self.groupBox)
        self.btnHwDisconnect.setObjectName("btnHwDisconnect")
        self.layHardwareWallet.addWidget(self.btnHwDisconnect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layHardwareWallet.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.layHardwareWallet)
        self.layMessage = QtWidgets.QHBoxLayout()
        self.layMessage.setContentsMargins(0, -1, -1, 0)
        self.layMessage.setSpacing(0)
        self.layMessage.setObjectName("layMessage")
        self.lblMessage = QtWidgets.QLabel(self.groupBox)
        self.lblMessage.setText("")
        self.lblMessage.setWordWrap(True)
        self.lblMessage.setOpenExternalLinks(True)
        self.lblMessage.setObjectName("lblMessage")
        self.layMessage.addWidget(self.lblMessage)
        self.verticalLayout_2.addLayout(self.layMessage)
        self.horizontalLayout_11.addWidget(self.groupBox)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setSpacing(3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lblAbout = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAbout.sizePolicy().hasHeightForWidth())
        self.lblAbout.setSizePolicy(sizePolicy)
        self.lblAbout.setMinimumSize(QtCore.QSize(64, 64))
        self.lblAbout.setMaximumSize(QtCore.QSize(64, 64))
        self.lblAbout.setText("")
        self.lblAbout.setObjectName("lblAbout")
        self.horizontalLayout_13.addWidget(self.lblAbout)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_11.setStretch(0, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 1, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.masternode_box = QtWidgets.QGroupBox(self.tab)
        self.masternode_box.setGeometry(QtCore.QRect(0, 10, 885, 293))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.masternode_box.sizePolicy().hasHeightForWidth())
        self.masternode_box.setSizePolicy(sizePolicy)
        self.masternode_box.setTitle("")
        self.masternode_box.setObjectName("masternode_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.masternode_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(3)
        self.gridLayout_2.setVerticalSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cboMasternodes = QtWidgets.QComboBox(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboMasternodes.sizePolicy().hasHeightForWidth())
        self.cboMasternodes.setSizePolicy(sizePolicy)
        self.cboMasternodes.setMinimumSize(QtCore.QSize(140, 0))
        self.cboMasternodes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cboMasternodes.setEditable(False)
        self.cboMasternodes.setObjectName("cboMasternodes")
        self.horizontalLayout_4.addWidget(self.cboMasternodes)
        self.btnNewMn = QtWidgets.QPushButton(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewMn.sizePolicy().hasHeightForWidth())
        self.btnNewMn.setSizePolicy(sizePolicy)
        self.btnNewMn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnNewMn.setObjectName("btnNewMn")
        self.horizontalLayout_4.addWidget(self.btnNewMn)
        self.btnDeleteMn = QtWidgets.QPushButton(self.masternode_box)
        self.btnDeleteMn.setObjectName("btnDeleteMn")
        self.horizontalLayout_4.addWidget(self.btnDeleteMn)
        self.btnEditMn = QtWidgets.QPushButton(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditMn.sizePolicy().hasHeightForWidth())
        self.btnEditMn.setSizePolicy(sizePolicy)
        self.btnEditMn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnEditMn.setObjectName("btnEditMn")
        self.horizontalLayout_4.addWidget(self.btnEditMn)
        self.btnImportMasternodesConf = QtWidgets.QPushButton(self.masternode_box)
        self.btnImportMasternodesConf.setObjectName("btnImportMasternodesConf")
        self.horizontalLayout_4.addWidget(self.btnImportMasternodesConf)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edtMnIp = QtWidgets.QLineEdit(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMnIp.sizePolicy().hasHeightForWidth())
        self.edtMnIp.setSizePolicy(sizePolicy)
        self.edtMnIp.setMinimumSize(QtCore.QSize(0, 0))
        self.edtMnIp.setMaximumSize(QtCore.QSize(150, 16777215))
        self.edtMnIp.setObjectName("edtMnIp")
        self.horizontalLayout_3.addWidget(self.edtMnIp)
        self.label_11 = QtWidgets.QLabel(self.masternode_box)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.edtMnPort = QtWidgets.QLineEdit(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMnPort.sizePolicy().hasHeightForWidth())
        self.edtMnPort.setSizePolicy(sizePolicy)
        self.edtMnPort.setMinimumSize(QtCore.QSize(0, 0))
        self.edtMnPort.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMnPort.setObjectName("edtMnPort")
        self.horizontalLayout_3.addWidget(self.edtMnPort)
        self.chbUseDefaultProtocolVersion = QtWidgets.QCheckBox(self.masternode_box)
        self.chbUseDefaultProtocolVersion.setObjectName("chbUseDefaultProtocolVersion")
        self.horizontalLayout_3.addWidget(self.chbUseDefaultProtocolVersion)
        self.edtMnProtocolVersion = QtWidgets.QLineEdit(self.masternode_box)
        self.edtMnProtocolVersion.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edtMnProtocolVersion.setStatusTip("")
        self.edtMnProtocolVersion.setObjectName("edtMnProtocolVersion")
        self.horizontalLayout_3.addWidget(self.edtMnProtocolVersion)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.edtMnCollateralTx = QtWidgets.QLineEdit(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMnCollateralTx.sizePolicy().hasHeightForWidth())
        self.edtMnCollateralTx.setSizePolicy(sizePolicy)
        self.edtMnCollateralTx.setMinimumSize(QtCore.QSize(300, 0))
        self.edtMnCollateralTx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtMnCollateralTx.setText("")
        self.edtMnCollateralTx.setObjectName("edtMnCollateralTx")
        self.horizontalLayout_7.addWidget(self.edtMnCollateralTx)
        self.label_7 = QtWidgets.QLabel(self.masternode_box)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.edtMnCollateralTxIndex = QtWidgets.QLineEdit(self.masternode_box)
        self.edtMnCollateralTxIndex.setMaximumSize(QtCore.QSize(25, 16777215))
        self.edtMnCollateralTxIndex.setObjectName("edtMnCollateralTxIndex")
        self.horizontalLayout_7.addWidget(self.edtMnCollateralTxIndex)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 5, 1, 1, 1)
        self.layCollateral = QtWidgets.QHBoxLayout()
        self.layCollateral.setContentsMargins(-1, 0, -1, 0)
        self.layCollateral.setSpacing(0)
        self.layCollateral.setObjectName("layCollateral")
        self.edtMnCollateralAddress = QtWidgets.QLineEdit(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMnCollateralAddress.sizePolicy().hasHeightForWidth())
        self.edtMnCollateralAddress.setSizePolicy(sizePolicy)
        self.edtMnCollateralAddress.setMinimumSize(QtCore.QSize(0, 0))
        self.edtMnCollateralAddress.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtMnCollateralAddress.setReadOnly(False)
        self.edtMnCollateralAddress.setObjectName("edtMnCollateralAddress")
        self.layCollateral.addWidget(self.edtMnCollateralAddress)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnHwMnAddressToBip32 = QtWidgets.QPushButton(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHwMnAddressToBip32.sizePolicy().hasHeightForWidth())
        self.btnHwMnAddressToBip32.setSizePolicy(sizePolicy)
        self.btnHwMnAddressToBip32.setMinimumSize(QtCore.QSize(30, 0))
        self.btnHwMnAddressToBip32.setMaximumSize(QtCore.QSize(10000, 1000000))
        self.btnHwMnAddressToBip32.setText("")
        self.btnHwMnAddressToBip32.setIconSize(QtCore.QSize(16, 16))
        self.btnHwMnAddressToBip32.setObjectName("btnHwMnAddressToBip32")
        self.horizontalLayout_2.addWidget(self.btnHwMnAddressToBip32)
        self.btnHwBip32ToMnAddress = QtWidgets.QPushButton(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHwBip32ToMnAddress.sizePolicy().hasHeightForWidth())
        self.btnHwBip32ToMnAddress.setSizePolicy(sizePolicy)
        self.btnHwBip32ToMnAddress.setMinimumSize(QtCore.QSize(30, 0))
        self.btnHwBip32ToMnAddress.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.btnHwBip32ToMnAddress.setText("")
        self.btnHwBip32ToMnAddress.setIconSize(QtCore.QSize(16, 16))
        self.btnHwBip32ToMnAddress.setObjectName("btnHwBip32ToMnAddress")
        self.horizontalLayout_2.addWidget(self.btnHwBip32ToMnAddress)
        self.layCollateral.addLayout(self.horizontalLayout_2)
        self.edtMnCollateralBip32Path = QtWidgets.QLineEdit(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMnCollateralBip32Path.sizePolicy().hasHeightForWidth())
        self.edtMnCollateralBip32Path.setSizePolicy(sizePolicy)
        self.edtMnCollateralBip32Path.setMinimumSize(QtCore.QSize(0, 0))
        self.edtMnCollateralBip32Path.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtMnCollateralBip32Path.setObjectName("edtMnCollateralBip32Path")
        self.layCollateral.addWidget(self.edtMnCollateralBip32Path, 0, QtCore.Qt.AlignVCenter)
        self.layCollateral.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.layCollateral, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.masternode_box)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.masternode_box)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.masternode_box)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.masternode_box)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.edtMnName = QtWidgets.QLineEdit(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMnName.sizePolicy().hasHeightForWidth())
        self.edtMnName.setSizePolicy(sizePolicy)
        self.edtMnName.setMinimumSize(QtCore.QSize(0, 0))
        self.edtMnName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtMnName.setObjectName("edtMnName")
        self.gridLayout_2.addWidget(self.edtMnName, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.masternode_box)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.btnGenerateMNPrivateKey = QtWidgets.QPushButton(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGenerateMNPrivateKey.sizePolicy().hasHeightForWidth())
        self.btnGenerateMNPrivateKey.setSizePolicy(sizePolicy)
        self.btnGenerateMNPrivateKey.setMinimumSize(QtCore.QSize(110, 0))
        self.btnGenerateMNPrivateKey.setMaximumSize(QtCore.QSize(400, 16777215))
        self.btnGenerateMNPrivateKey.setObjectName("btnGenerateMNPrivateKey")
        self.gridLayout_2.addWidget(self.btnGenerateMNPrivateKey, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.masternode_box)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.masternode_box)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 7, 0, 1, 1)
        self.edtMnPrivateKey = QtWidgets.QLineEdit(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMnPrivateKey.sizePolicy().hasHeightForWidth())
        self.edtMnPrivateKey.setSizePolicy(sizePolicy)
        self.edtMnPrivateKey.setMinimumSize(QtCore.QSize(0, 0))
        self.edtMnPrivateKey.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtMnPrivateKey.setObjectName("edtMnPrivateKey")
        self.gridLayout_2.addWidget(self.edtMnPrivateKey, 3, 1, 1, 1)
        self.btnRefreshMnStatus = QtWidgets.QPushButton(self.masternode_box)
        self.btnRefreshMnStatus.setObjectName("btnRefreshMnStatus")
        self.gridLayout_2.addWidget(self.btnRefreshMnStatus, 6, 3, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.btnBroadcastMn = QtWidgets.QPushButton(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBroadcastMn.sizePolicy().hasHeightForWidth())
        self.btnBroadcastMn.setSizePolicy(sizePolicy)
        self.btnBroadcastMn.setMinimumSize(QtCore.QSize(0, 0))
        self.btnBroadcastMn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnBroadcastMn.setStyleSheet("")
        self.btnBroadcastMn.setObjectName("btnBroadcastMn")
        self.horizontalLayout_12.addWidget(self.btnBroadcastMn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.horizontalLayout_12.setStretch(1, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 7, 1, 1, 1)
        self.btnFindMnCollateral = QtWidgets.QPushButton(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFindMnCollateral.sizePolicy().hasHeightForWidth())
        self.btnFindMnCollateral.setSizePolicy(sizePolicy)
        self.btnFindMnCollateral.setMinimumSize(QtCore.QSize(0, 0))
        self.btnFindMnCollateral.setObjectName("btnFindMnCollateral")
        self.gridLayout_2.addWidget(self.btnFindMnCollateral, 5, 3, 1, 1)
        self.lblMnStatus = QtWidgets.QLabel(self.masternode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lblMnStatus.sizePolicy().hasHeightForWidth())
        self.lblMnStatus.setSizePolicy(sizePolicy)
        self.lblMnStatus.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblMnStatus.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblMnStatus.setLineWidth(1)
        self.lblMnStatus.setText("")
        self.lblMnStatus.setWordWrap(True)
        self.lblMnStatus.setObjectName("lblMnStatus")
        self.gridLayout_2.addWidget(self.lblMnStatus, 6, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.systemnode_box = QtWidgets.QGroupBox(self.tab_2)
        self.systemnode_box.setGeometry(QtCore.QRect(0, 10, 885, 293))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.systemnode_box.sizePolicy().hasHeightForWidth())
        self.systemnode_box.setSizePolicy(sizePolicy)
        self.systemnode_box.setTitle("")
        self.systemnode_box.setObjectName("systemnode_box")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.systemnode_box)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(3)
        self.gridLayout_4.setVerticalSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cboSystemnodes = QtWidgets.QComboBox(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSystemnodes.sizePolicy().hasHeightForWidth())
        self.cboSystemnodes.setSizePolicy(sizePolicy)
        self.cboSystemnodes.setMinimumSize(QtCore.QSize(140, 0))
        self.cboSystemnodes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cboSystemnodes.setEditable(False)
        self.cboSystemnodes.setObjectName("cboSystemnodes")
        self.horizontalLayout_6.addWidget(self.cboSystemnodes)
        self.btnNewSn = QtWidgets.QPushButton(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewSn.sizePolicy().hasHeightForWidth())
        self.btnNewSn.setSizePolicy(sizePolicy)
        self.btnNewSn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnNewSn.setObjectName("btnNewSn")
        self.horizontalLayout_6.addWidget(self.btnNewSn)
        self.btnDeleteSn = QtWidgets.QPushButton(self.systemnode_box)
        self.btnDeleteSn.setObjectName("btnDeleteSn")
        self.horizontalLayout_6.addWidget(self.btnDeleteSn)
        self.btnEditSn = QtWidgets.QPushButton(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditSn.sizePolicy().hasHeightForWidth())
        self.btnEditSn.setSizePolicy(sizePolicy)
        self.btnEditSn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnEditSn.setObjectName("btnEditSn")
        self.horizontalLayout_6.addWidget(self.btnEditSn)
        self.btnImportSystemnodesConf = QtWidgets.QPushButton(self.systemnode_box)
        self.btnImportSystemnodesConf.setObjectName("btnImportSystemnodesConf")
        self.horizontalLayout_6.addWidget(self.btnImportSystemnodesConf)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.edtSnIp = QtWidgets.QLineEdit(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSnIp.sizePolicy().hasHeightForWidth())
        self.edtSnIp.setSizePolicy(sizePolicy)
        self.edtSnIp.setMinimumSize(QtCore.QSize(0, 0))
        self.edtSnIp.setMaximumSize(QtCore.QSize(150, 16777215))
        self.edtSnIp.setObjectName("edtSnIp")
        self.horizontalLayout_8.addWidget(self.edtSnIp)
        self.label_13 = QtWidgets.QLabel(self.systemnode_box)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.edtSnPort = QtWidgets.QLineEdit(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSnPort.sizePolicy().hasHeightForWidth())
        self.edtSnPort.setSizePolicy(sizePolicy)
        self.edtSnPort.setMinimumSize(QtCore.QSize(0, 0))
        self.edtSnPort.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtSnPort.setObjectName("edtSnPort")
        self.horizontalLayout_8.addWidget(self.edtSnPort)
        self.chbUseDefaultProtocolVersionSN = QtWidgets.QCheckBox(self.systemnode_box)
        self.chbUseDefaultProtocolVersionSN.setObjectName("chbUseDefaultProtocolVersionSN")
        self.horizontalLayout_8.addWidget(self.chbUseDefaultProtocolVersionSN)
        self.edtSnProtocolVersion = QtWidgets.QLineEdit(self.systemnode_box)
        self.edtSnProtocolVersion.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edtSnProtocolVersion.setStatusTip("")
        self.edtSnProtocolVersion.setObjectName("edtSnProtocolVersion")
        self.horizontalLayout_8.addWidget(self.edtSnProtocolVersion)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.edtSnCollateralTx = QtWidgets.QLineEdit(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSnCollateralTx.sizePolicy().hasHeightForWidth())
        self.edtSnCollateralTx.setSizePolicy(sizePolicy)
        self.edtSnCollateralTx.setMinimumSize(QtCore.QSize(300, 0))
        self.edtSnCollateralTx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtSnCollateralTx.setText("")
        self.edtSnCollateralTx.setObjectName("edtSnCollateralTx")
        self.horizontalLayout_9.addWidget(self.edtSnCollateralTx)
        self.label_14 = QtWidgets.QLabel(self.systemnode_box)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.edtSnCollateralTxIndex = QtWidgets.QLineEdit(self.systemnode_box)
        self.edtSnCollateralTxIndex.setMaximumSize(QtCore.QSize(25, 16777215))
        self.edtSnCollateralTxIndex.setObjectName("edtSnCollateralTxIndex")
        self.horizontalLayout_9.addWidget(self.edtSnCollateralTxIndex)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 5, 1, 1, 1)
        self.layCollateralSN = QtWidgets.QHBoxLayout()
        self.layCollateralSN.setContentsMargins(-1, 0, -1, 0)
        self.layCollateralSN.setSpacing(0)
        self.layCollateralSN.setObjectName("layCollateralSN")
        self.edtSnCollateralAddress = QtWidgets.QLineEdit(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSnCollateralAddress.sizePolicy().hasHeightForWidth())
        self.edtSnCollateralAddress.setSizePolicy(sizePolicy)
        self.edtSnCollateralAddress.setMinimumSize(QtCore.QSize(0, 0))
        self.edtSnCollateralAddress.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtSnCollateralAddress.setReadOnly(False)
        self.edtSnCollateralAddress.setObjectName("edtSnCollateralAddress")
        self.layCollateralSN.addWidget(self.edtSnCollateralAddress)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_10.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnHwSnAddressToBip32 = QtWidgets.QPushButton(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHwSnAddressToBip32.sizePolicy().hasHeightForWidth())
        self.btnHwSnAddressToBip32.setSizePolicy(sizePolicy)
        self.btnHwSnAddressToBip32.setMinimumSize(QtCore.QSize(30, 0))
        self.btnHwSnAddressToBip32.setMaximumSize(QtCore.QSize(10000, 1000000))
        self.btnHwSnAddressToBip32.setText("")
        self.btnHwSnAddressToBip32.setIconSize(QtCore.QSize(16, 16))
        self.btnHwSnAddressToBip32.setObjectName("btnHwSnAddressToBip32")
        self.horizontalLayout_10.addWidget(self.btnHwSnAddressToBip32)
        self.btnHwBip32ToSnAddress = QtWidgets.QPushButton(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHwBip32ToSnAddress.sizePolicy().hasHeightForWidth())
        self.btnHwBip32ToSnAddress.setSizePolicy(sizePolicy)
        self.btnHwBip32ToSnAddress.setMinimumSize(QtCore.QSize(30, 0))
        self.btnHwBip32ToSnAddress.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.btnHwBip32ToSnAddress.setText("")
        self.btnHwBip32ToSnAddress.setIconSize(QtCore.QSize(16, 16))
        self.btnHwBip32ToSnAddress.setObjectName("btnHwBip32ToSnAddress")
        self.horizontalLayout_10.addWidget(self.btnHwBip32ToSnAddress)
        self.layCollateralSN.addLayout(self.horizontalLayout_10)
        self.edtSnCollateralBip32Path = QtWidgets.QLineEdit(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSnCollateralBip32Path.sizePolicy().hasHeightForWidth())
        self.edtSnCollateralBip32Path.setSizePolicy(sizePolicy)
        self.edtSnCollateralBip32Path.setMinimumSize(QtCore.QSize(0, 0))
        self.edtSnCollateralBip32Path.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtSnCollateralBip32Path.setObjectName("edtSnCollateralBip32Path")
        self.layCollateralSN.addWidget(self.edtSnCollateralBip32Path, 0, QtCore.Qt.AlignVCenter)
        self.layCollateralSN.setStretch(0, 1)
        self.gridLayout_4.addLayout(self.layCollateralSN, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.systemnode_box)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.systemnode_box)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.systemnode_box)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.systemnode_box)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)
        self.edtSnName = QtWidgets.QLineEdit(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSnName.sizePolicy().hasHeightForWidth())
        self.edtSnName.setSizePolicy(sizePolicy)
        self.edtSnName.setMinimumSize(QtCore.QSize(0, 0))
        self.edtSnName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtSnName.setObjectName("edtSnName")
        self.gridLayout_4.addWidget(self.edtSnName, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.systemnode_box)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 5, 0, 1, 1)
        self.btnGenerateSNPrivateKey = QtWidgets.QPushButton(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGenerateSNPrivateKey.sizePolicy().hasHeightForWidth())
        self.btnGenerateSNPrivateKey.setSizePolicy(sizePolicy)
        self.btnGenerateSNPrivateKey.setMinimumSize(QtCore.QSize(110, 0))
        self.btnGenerateSNPrivateKey.setMaximumSize(QtCore.QSize(400, 16777215))
        self.btnGenerateSNPrivateKey.setObjectName("btnGenerateSNPrivateKey")
        self.gridLayout_4.addWidget(self.btnGenerateSNPrivateKey, 3, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.systemnode_box)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.systemnode_box)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 7, 0, 1, 1)
        self.edtSnPrivateKey = QtWidgets.QLineEdit(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSnPrivateKey.sizePolicy().hasHeightForWidth())
        self.edtSnPrivateKey.setSizePolicy(sizePolicy)
        self.edtSnPrivateKey.setMinimumSize(QtCore.QSize(0, 0))
        self.edtSnPrivateKey.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtSnPrivateKey.setObjectName("edtSnPrivateKey")
        self.gridLayout_4.addWidget(self.edtSnPrivateKey, 3, 1, 1, 1)
        self.btnRefreshSnStatus = QtWidgets.QPushButton(self.systemnode_box)
        self.btnRefreshSnStatus.setObjectName("btnRefreshSnStatus")
        self.gridLayout_4.addWidget(self.btnRefreshSnStatus, 6, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.btnBroadcastSn = QtWidgets.QPushButton(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBroadcastSn.sizePolicy().hasHeightForWidth())
        self.btnBroadcastSn.setSizePolicy(sizePolicy)
        self.btnBroadcastSn.setMinimumSize(QtCore.QSize(0, 0))
        self.btnBroadcastSn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnBroadcastSn.setStyleSheet("")
        self.btnBroadcastSn.setObjectName("btnBroadcastSn")
        self.horizontalLayout_14.addWidget(self.btnBroadcastSn)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.horizontalLayout_14.setStretch(1, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 7, 1, 1, 1)
        self.btnFindSnCollateral = QtWidgets.QPushButton(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFindSnCollateral.sizePolicy().hasHeightForWidth())
        self.btnFindSnCollateral.setSizePolicy(sizePolicy)
        self.btnFindSnCollateral.setMinimumSize(QtCore.QSize(0, 0))
        self.btnFindSnCollateral.setObjectName("btnFindSnCollateral")
        self.gridLayout_4.addWidget(self.btnFindSnCollateral, 5, 3, 1, 1)
        self.lblSnStatus = QtWidgets.QLabel(self.systemnode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lblSnStatus.sizePolicy().hasHeightForWidth())
        self.lblSnStatus.setSizePolicy(sizePolicy)
        self.lblSnStatus.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblSnStatus.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblSnStatus.setLineWidth(1)
        self.lblSnStatus.setText("")
        self.lblSnStatus.setWordWrap(True)
        self.lblSnStatus.setObjectName("lblSnStatus")
        self.gridLayout_4.addWidget(self.lblSnStatus, 6, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnCheckConnection, self.btnConfiguration)
        MainWindow.setTabOrder(self.btnConfiguration, self.btnSaveConfiguration)
        MainWindow.setTabOrder(self.btnSaveConfiguration, self.btnActions)
        MainWindow.setTabOrder(self.btnActions, self.btnAbout)
        MainWindow.setTabOrder(self.btnAbout, self.btnHwCheck)
        MainWindow.setTabOrder(self.btnHwCheck, self.btnHwDisconnect)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCheckConnection.setToolTip(_translate("MainWindow", "Check connection with Crown daemon"))
        self.btnCheckConnection.setText(_translate("MainWindow", "Check RPC connection"))
        self.btnConfiguration.setToolTip(_translate("MainWindow", "Open configuration window of communication with a Crown daemon"))
        self.btnConfiguration.setText(_translate("MainWindow", "Configure"))
        self.btnSaveConfiguration.setText(_translate("MainWindow", "Save configuration"))
        self.btnProposals.setText(_translate("MainWindow", "Proposals"))
        self.btnActions.setText(_translate("MainWindow", "Tools"))
        self.btnAbout.setText(_translate("MainWindow", "About"))
        self.btnHwCheck.setToolTip(_translate("MainWindow", "Check hardware wallet connection"))
        self.btnHwCheck.setText(_translate("MainWindow", "Test HW"))
        self.btnHwDisconnect.setToolTip(_translate("MainWindow", "Close hardware wallet session "))
        self.btnHwDisconnect.setText(_translate("MainWindow", "Disconnect HW"))
        self.cboMasternodes.setToolTip(_translate("MainWindow", "List of configured masternodes"))
        self.btnNewMn.setToolTip(_translate("MainWindow", "Create a new Masternode configuration"))
        self.btnNewMn.setText(_translate("MainWindow", "New"))
        self.btnDeleteMn.setToolTip(_translate("MainWindow", "Delete current Masternode configuration"))
        self.btnDeleteMn.setText(_translate("MainWindow", "Delete"))
        self.btnEditMn.setToolTip(_translate("MainWindow", "Enable editing"))
        self.btnEditMn.setText(_translate("MainWindow", "Edit"))
        self.btnImportMasternodesConf.setToolTip(_translate("MainWindow", "Import Masternodes from masternode.conf file"))
        self.btnImportMasternodesConf.setText(_translate("MainWindow", "Import"))
        self.edtMnIp.setToolTip(_translate("MainWindow", "The Masternode\'s IP address for incoming communication with other nodes"))
        self.label_11.setText(_translate("MainWindow", "port:"))
        self.edtMnPort.setToolTip(_translate("MainWindow", "The Masternode\'s TCP port number for incoming communication with other nodes"))
        self.chbUseDefaultProtocolVersion.setToolTip(_translate("MainWindow", "Use the protocol version number (from the RPC node) when starting masternode"))
        self.chbUseDefaultProtocolVersion.setText(_translate("MainWindow", "Use default protocol version"))
        self.edtMnProtocolVersion.setToolTip(_translate("MainWindow", "Enter the protocol version number to be sent at masternode start time"))
        self.edtMnProtocolVersion.setInputMask(_translate("MainWindow", "00009"))
        self.edtMnProtocolVersion.setPlaceholderText(_translate("MainWindow", "default"))
        self.edtMnCollateralTx.setToolTip(_translate("MainWindow", "The collateral transaction hash from the 10000 CRW deposit"))
        self.label_7.setText(_translate("MainWindow", "TX index:"))
        self.edtMnCollateralTxIndex.setToolTip(_translate("MainWindow", "The collateral transaction\'s (unspent) output index with the 10000 CRW deposit (usally 0)"))
        self.edtMnCollateralAddress.setToolTip(_translate("MainWindow", "Crown address of the 10000 CRW collateral, coverted from BIP32 path with hardware wallet."))
        self.edtMnCollateralAddress.setPlaceholderText(_translate("MainWindow", "Crown address"))
        self.btnHwMnAddressToBip32.setToolTip(_translate("MainWindow", "Convert Crown address to BIP32 path using hardware wallet"))
        self.btnHwBip32ToMnAddress.setToolTip(_translate("MainWindow", "Convert BIP32 path to Crown address using hardware wallet"))
        self.edtMnCollateralBip32Path.setToolTip(_translate("MainWindow", "BIP32 path of the 10000 CRW collateral (e.g. 44\'/83\'/0\'/0/0)"))
        self.edtMnCollateralBip32Path.setPlaceholderText(_translate("MainWindow", "BIP32 path"))
        self.label_4.setText(_translate("MainWindow", "Collateral:"))
        self.label_9.setText(_translate("MainWindow", "MN private key:"))
        self.label_8.setText(_translate("MainWindow", "Masternode status:"))
        self.label_12.setText(_translate("MainWindow", "Name:"))
        self.edtMnName.setToolTip(_translate("MainWindow", "The Masternode\'s configuration name"))
        self.label_6.setText(_translate("MainWindow", "Collateral TX ID:"))
        self.btnGenerateMNPrivateKey.setToolTip(_translate("MainWindow", "Generate a new private key"))
        self.btnGenerateMNPrivateKey.setText(_translate("MainWindow", "Generate new"))
        self.label_5.setText(_translate("MainWindow", "Masternode:"))
        self.label_10.setText(_translate("MainWindow", "IP:"))
        self.edtMnPrivateKey.setToolTip(_translate("MainWindow", "Masternode\'s private key. Use your own or click the button <Generate new> to create a new and random private key with the use of \'bitcoin\' library."))
        self.btnRefreshMnStatus.setToolTip(_translate("MainWindow", "Get Masternode\'s status"))
        self.btnRefreshMnStatus.setText(_translate("MainWindow", "Get status"))
        self.btnBroadcastMn.setToolTip(_translate("MainWindow", "Broadcast information about the Masternode"))
        self.btnBroadcastMn.setText(_translate("MainWindow", "Start Masternode using hardware wallet"))
        self.btnFindMnCollateral.setToolTip(_translate("MainWindow", "Find collateral transaction"))
        self.btnFindMnCollateral.setText(_translate("MainWindow", "Lookup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Masternodes"))
        self.cboSystemnodes.setToolTip(_translate("MainWindow", "List of configured systemnodes"))
        self.btnNewSn.setToolTip(_translate("MainWindow", "Create a new Systemnode configuration"))
        self.btnNewSn.setText(_translate("MainWindow", "New"))
        self.btnDeleteSn.setToolTip(_translate("MainWindow", "Delete current Systemnode configuration"))
        self.btnDeleteSn.setText(_translate("MainWindow", "Delete"))
        self.btnEditSn.setToolTip(_translate("MainWindow", "Enable editing"))
        self.btnEditSn.setText(_translate("MainWindow", "Edit"))
        self.btnImportSystemnodesConf.setToolTip(_translate("MainWindow", "Import systemnodes from systemnode.conf file"))
        self.btnImportSystemnodesConf.setText(_translate("MainWindow", "Import"))
        self.edtSnIp.setToolTip(_translate("MainWindow", "The Systemnode\'s IP address for incoming communication with other nodes"))
        self.label_13.setText(_translate("MainWindow", "port:"))
        self.edtSnPort.setToolTip(_translate("MainWindow", "The Systemnode\'s TCP port number for incoming communication with other nodes"))
        self.chbUseDefaultProtocolVersionSN.setToolTip(_translate("MainWindow", "Use the protocol version number (from the RPC node) when starting systemnode"))
        self.chbUseDefaultProtocolVersionSN.setText(_translate("MainWindow", "Use default protocol version"))
        self.edtSnProtocolVersion.setToolTip(_translate("MainWindow", "Enter the protocol version number to be sent at systemnode start time"))
        self.edtSnProtocolVersion.setInputMask(_translate("MainWindow", "00009"))
        self.edtSnProtocolVersion.setPlaceholderText(_translate("MainWindow", "default"))
        self.edtSnCollateralTx.setToolTip(_translate("MainWindow", "The collateral transaction hash from the 500 CRW deposit"))
        self.label_14.setText(_translate("MainWindow", "TX index:"))
        self.edtSnCollateralTxIndex.setToolTip(_translate("MainWindow", "The collateral transaction\'s (unspent) output index with the 500 CRW deposit (usally 0)"))
        self.edtSnCollateralAddress.setToolTip(_translate("MainWindow", "Crown address of the 500 CRW collateral, coverted from BIP32 path with hardware wallet."))
        self.edtSnCollateralAddress.setPlaceholderText(_translate("MainWindow", "Crown address"))
        self.btnHwSnAddressToBip32.setToolTip(_translate("MainWindow", "Convert Crown address to BIP32 path using hardware wallet"))
        self.btnHwBip32ToSnAddress.setToolTip(_translate("MainWindow", "Convert BIP32 path to Crown address using hardware wallet"))
        self.edtSnCollateralBip32Path.setToolTip(_translate("MainWindow", "BIP32 path of the 500 CRW collateral (e.g. 44\'/83\'/0\'/0/0)"))
        self.edtSnCollateralBip32Path.setPlaceholderText(_translate("MainWindow", "BIP32 path"))
        self.label_15.setText(_translate("MainWindow", "Collateral:"))
        self.label_16.setText(_translate("MainWindow", "SN private key:"))
        self.label_17.setText(_translate("MainWindow", "Systemnode status:"))
        self.label_18.setText(_translate("MainWindow", "Name:"))
        self.edtSnName.setToolTip(_translate("MainWindow", "The Systemnode\'s configuration name"))
        self.label_19.setText(_translate("MainWindow", "Collateral TX ID:"))
        self.btnGenerateSNPrivateKey.setToolTip(_translate("MainWindow", "Generate a new private key"))
        self.btnGenerateSNPrivateKey.setText(_translate("MainWindow", "Generate new"))
        self.label_20.setText(_translate("MainWindow", "Systemnode:"))
        self.label_21.setText(_translate("MainWindow", "IP:"))
        self.edtSnPrivateKey.setToolTip(_translate("MainWindow", "Systemnode\'s private key. Use your own or click the button <Generate new> to create a new and random private key with the use of \'bitcoin\' library."))
        self.btnRefreshSnStatus.setToolTip(_translate("MainWindow", "Get Systemnode\'s status"))
        self.btnRefreshSnStatus.setText(_translate("MainWindow", "Get status"))
        self.btnBroadcastSn.setToolTip(_translate("MainWindow", "Broadcast information about the Systemnode"))
        self.btnBroadcastSn.setText(_translate("MainWindow", "Start Systemnode using hardware wallet"))
        self.btnFindSnCollateral.setToolTip(_translate("MainWindow", "Find collateral transaction"))
        self.btnFindSnCollateral.setText(_translate("MainWindow", "Lookup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Systemnodes"))

